# Generated by Django 2.1 on 2019-10-23 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Propuesta')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre del Proyecto')),
                ('fechaa', models.DateField(default=datetime.date.today, verbose_name='Fecha de Autorizacion (SDA)')),
                ('fechai', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio')),
                ('fechat', models.DateField(default=datetime.date.today, verbose_name='Fecha de Termino')),
                ('Adjuntar_Archivo', models.FileField(blank=True, upload_to='proyectos', verbose_name='Adjuntar Proyecto')),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripcion')),
                ('duracion', models.IntegerField(verbose_name='Duracion (Semanas)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Propuestas de Proyectos',
            },
        ),
    ]
