# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectos',
            options={'ordering': ['-id'], 'verbose_name': 'Propuestas de Proyectos'},
        ),
    ]
