# Generated by Django 2.1 on 2019-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infraestructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(blank=True, max_length=50, verbose_name='Sistema')),
                ('ubicacion', models.CharField(blank=True, max_length=50, verbose_name='Ubicacion')),
                ('frecuencia', models.IntegerField(verbose_name='Frecuencia')),
                ('responsable', models.CharField(blank=True, max_length=50, verbose_name='Responsable')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
