# Generated by Django 2.1 on 2019-10-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestructura',
            name='sistema',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sistema'),
        ),
    ]
