# Generated by Django 2.2.4 on 2019-08-22 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio Clinico')),
                ('clase', models.CharField(max_length=100, verbose_name='Clase')),
                ('subclase', models.CharField(max_length=100, verbose_name='Subclase')),
                ('nombre_equipo', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Numero de Serie')),
                ('inventario', models.CharField(max_length=100, verbose_name='Numero Inventario')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor el Equipo')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Instalacion')),
                ('vida_util', models.IntegerField(max_length=100, verbose_name='Vida Util')),
                ('contrato', models.CharField(choices=[('ARRIENDO', 'Arriendo'), ('COMODATO', 'Comodato'), ('PROPIO', 'Propio')], default='PROPIO', max_length=10, verbose_name='Tipo de Contrato')),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo')], default='B', max_length=1, verbose_name='Condicion del Equipo')),
                ('critico_apoyo', models.CharField(choices=[('C', 'Critico'), ('A', 'Apoyo')], default='A', max_length=1, verbose_name='Critico/Apoyo')),
                ('frecuencia', models.IntegerField(max_length=10, verbose_name='Frecuencia de Mantenimiento')),
                ('empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('rut', models.CharField(max_length=15, verbose_name='RUT de la Empresa')),
                ('garantia_inicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio de la Garantia')),
                ('garantia_final', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio de Termino')),
                ('fecha_baja', models.DateField(default=datetime.date.today, verbose_name='Fecha de Baja')),
                ('mantenciones_realizadas', models.IntegerField(max_length=10, verbose_name='Numero de Mantenciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
