# Generated by Django 2.2.1 on 2019-08-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_baja',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
