# Generated by Django 2.2.1 on 2019-08-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190824_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='frecuencia',
            field=models.IntegerField(verbose_name='Frecuencia de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='mantenciones_realizadas',
            field=models.IntegerField(verbose_name='Numero de Mantenciones'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='vida_util',
            field=models.IntegerField(verbose_name='Vida Util'),
        ),
    ]
