# Generated by Django 2.2.1 on 2019-08-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190829_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='mantenciones_realizadas',
        ),
    ]
