# Generated by Django 2.2.5 on 2019-10-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_inventario_mantenciones_realizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Adjuntar_Archivo',
            field=models.FileField(blank=True, default='NULL', upload_to='inventario', verbose_name='Adjuntar Archivo'),
        ),
    ]
