# Generated by Django 2.2.5 on 2019-10-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_inventario_adjuntar_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='licitacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de Licitacion'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Adjuntar_Archivo',
            field=models.FileField(blank=True, upload_to='inventario', verbose_name='Adjuntar Archivo'),
        ),
    ]
