# Generated by Django 2.1 on 2019-10-24 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20191010_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='clase',
            field=models.CharField(choices=[('Apoyo Diagnóstico', 'APOYO DIAGNOSTICO'), ('Apoyo Endoscópico', 'APOYO ENDOSCOPICO'), ('Apoyo Industrial', 'APOYO INDUSTRIAL'), ('Apoyo Quirúrgico', 'APOYO QUIRURGICO'), ('Apoyo Terapéutico', 'APOYO TERAPEUTICO'), ('Esterilización', 'ESTERILIZACION'), ('Imagenología', 'IMAGENOLOGIA'), ('Laboratorio/Farmac', 'LABORATORIO/FARMACIA'), ('Med. Fís. Rehabilitación', 'MED. FIS. REHABILITACION'), ('Monitoreo', 'MONITOREO'), ('Odontología', 'ODONTOLOGIA')], max_length=100, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('Baja', 'BAJA')], default='B', max_length=1, verbose_name='Condicion del Equipo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_baja',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='subclase',
            field=models.CharField(choices=[('Alto Costo', 'ALTO COSTO'), ('Mediano Costo', 'MEDIANO COSTO'), ('Bajo Costo', 'BAJO COSTO'), ('Instrumental', 'INSTRUMENTAL')], max_length=100, verbose_name='Subclase'),
        ),
    ]
