# Generated by Django 2.2.6 on 2019-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20191024_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='clase',
            field=models.CharField(choices=[('Apoyo Diagnóstico', 'APOYO DIAGNOSTICO'), ('Apoyo Endoscópico', 'APOYO ENDOSCOPICO'), ('Apoyo Industrial', 'APOYO INDUSTRIAL'), ('Apoyo Quirúrgico', 'APOYO QUIRURGICO'), ('Apoyo Terapéutico', 'APOYO TERAPEUTICO'), ('Esterilización', 'ESTERILIZACION'), ('Imagenología', 'IMAGENOLOGIA'), ('Laboratorio/Farmac', 'LABORATORIO/FARMACIA'), ('Med. Fís. Rehabilitación', 'MED. FIS. REHABILITACION'), ('Monitoreo', 'MONITOREO'), ('Odontología', 'ODONTOLOGIA'), ('Instrumental', 'INSTRUMENTAL')], max_length=100, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='subclase',
            field=models.CharField(choices=[('Alto Costo', 'ALTO COSTO'), ('Mediano Costo', 'MEDIANO COSTO'), ('Bajo Costo', 'BAJO COSTO')], max_length=100, verbose_name='Subclase'),
        ),
    ]
