# Generated by Django 2.2.6 on 2019-12-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20191112_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-id'], 'verbose_name': 'Inventario'},
        ),
        migrations.AddField(
            model_name='inventario',
            name='ano',
            field=models.IntegerField(default=1, verbose_name='Año de Instalacion'),
        ),
    ]
