# Generated by Django 2.2.6 on 2019-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20191209_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ano',
            field=models.IntegerField(verbose_name='Año de Instalacion'),
        ),
    ]
