# Generated by Django 2.2.6 on 2019-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20191209_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('Baja', 'BAJA')], default='B', max_length=5, verbose_name='Condicion del Equipo'),
        ),
    ]
