# Generated by Django 2.1 on 2019-10-21 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='Fecha_Adjudicacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Adjudicacion'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='Fecha_Publicacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Publicacion'),
        ),
    ]
