# Generated by Django 2.1 on 2019-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0002_auto_20191021_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
    ]
