# Generated by Django 2.1 on 2019-10-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0003_auto_20191021_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='estadolicitacion',
            field=models.CharField(blank=True, choices=[('Abierta', 'ABIERTA'), ('Cerrada', 'CERRADA'), ('Desierta', 'DESIERTA'), ('Adjudicada', 'ADJUDICADA'), ('Revocada', 'REVOCADA'), ('Suspendida', 'SUSPENDIDA')], default='', max_length=20, verbose_name='Estado de Licitacion'),
        ),
    ]
