# Generated by Django 2.2.6 on 2020-01-02 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacion', '0004_auto_20191021_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licitacion',
            options={'ordering': ['-id'], 'verbose_name': 'Licitaciones'},
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='Fecha_Adjudicacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Adjudicacion'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='Fecha_Publicacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='ID_Mercado_Publico',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Numero de Licitacion'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='Monto',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Monto Asignado'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='Nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre de Licitacion'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='adjudicado',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre del Adjudicado'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='detalle',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Detalle de Licitacion'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='fechatermino',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Termino'),
        ),
    ]
