# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colisiones', '0002_auto_20191107_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colisiones',
            options={'ordering': ['-id'], 'verbose_name': 'Colisiones'},
        ),
    ]
