# Generated by Django 2.1 on 2019-10-24 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriales',
            name='Clase',
            field=models.CharField(blank=True, choices=[('Apoyo Diagnóstico', 'APOYO DIAGNOSTICO'), ('Apoyo Endoscópico', 'APOYO ENDOSCOPICO'), ('Apoyo Industrial', 'APOYO INDUSTRIAL'), ('Apoyo Quirúrgico', 'APOYO QUIRURGICO'), ('Apoyo Terapéutico', 'APOYO TERAPEUTICO'), ('Esterilización', 'ESTERILIZACION'), ('Imagenología', 'IMAGENOLOGIA'), ('Laboratorio/Farmac', 'LABORATORIO/FARMACIA'), ('Med. Fís. Rehabilitación', 'MED. FIS. REHABILITACION'), ('Monitoreo', 'MONITOREO'), ('Odontología', 'ODONTOLOGIA')], max_length=100, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Nombre_Equipo',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Numero_Inventario',
            field=models.CharField(max_length=100, verbose_name='Numero de Inventario'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='RUT',
            field=models.CharField(blank=True, max_length=15, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Serie',
            field=models.CharField(max_length=100, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Servicio_Clinico',
            field=models.CharField(max_length=100, verbose_name='Servicio/Unidad'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Subclase',
            field=models.CharField(choices=[('Alto Costo', 'ALTO COSTO'), ('Mediano Costo', 'MEDIANO COSTO'), ('Bajo Costo', 'BAJO COSTO'), ('Instrumental', 'INSTRUMENTAL')], max_length=100, verbose_name='Subclase'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='criticoapoyo',
            field=models.CharField(blank=True, choices=[('Critico', 'CRITICO'), ('Apoyo', 'APOYO')], max_length=10, verbose_name='Critico/Apoyo'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='fechaBaja',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='fechaIG',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Inicio Garantia'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='fechaTG',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Termino de la Garantia'),
        ),
    ]
