# Generated by Django 2.1 on 2019-10-24 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriales', '0002_auto_20191024_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriales',
            name='Estado',
            field=models.CharField(blank=True, choices=[('Bueno', 'BUENO'), ('Malo', 'MALO'), ('Regular', 'REGULAR'), ('Baja', 'BAJA')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Responsable',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa Responsable'),
        ),
        migrations.AlterField(
            model_name='industriales',
            name='fechaBaja',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
