# Generated by Django 2.2.6 on 2020-01-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriales', '0003_auto_20191024_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industriales',
            options={'ordering': ['-id'], 'verbose_name': 'Inventario de Equipos Industriales'},
        ),
        migrations.AlterField(
            model_name='industriales',
            name='Numero_Inventario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de Inventario'),
        ),
    ]
