# Generated by Django 2.2.1 on 2019-08-29 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueAutomotriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movil', models.CharField(max_length=100)),
                ('Patente', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('inventario', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tecnico1', models.CharField(max_length=255)),
                ('tecnico2', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('km_anterior', models.CharField(max_length=100)),
                ('proximo_cambio', models.CharField(max_length=100)),
                ('km_programado', models.CharField(max_length=100)),
                ('km_real', models.CharField(max_length=100)),
                ('pauta1', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta2', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta3', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta4', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta5', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta6', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta7', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta8', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta9', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta10', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta11', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta12', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta13', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta14', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta15', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta16', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta17', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta18', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Parque Automotriz',
            },
        ),
    ]
