# Generated by Django 2.2.1 on 2019-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueautomotriz',
            name='Servicio',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
