# Generated by Django 2.2.1 on 2019-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0002_parqueautomotriz_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='Movil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='Patente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='Servicio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='inventario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='km_anterior',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='km_programado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='km_real',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='proximo_cambio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='responsable',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='tecnico1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='tecnico2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
