# Generated by Django 2.2.5 on 2019-09-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0003_auto_20190830_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueautomotriz',
            name='tecnico2',
        ),
    ]
