# Generated by Django 2.1 on 2019-10-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0007_auto_20191016_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='Patente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parqueautomotriz',
            name='marca',
            field=models.CharField(blank=True, default='Mercedes Benz', max_length=100),
        ),
    ]
