# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0008_auto_20191016_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parqueautomotriz',
            options={'ordering': ['-id'], 'verbose_name': 'Parque Automotriz'},
        ),
    ]
