# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roperiaconfeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roperiaconfeccion',
            options={'ordering': ['-id'], 'verbose_name': 'Boleta Confeccion de Ropa'},
        ),
    ]
