# Generated by Django 3.0.7 on 2020-06-26 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emsion')),
                ('fecharecepcion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Recepcion')),
                ('empresa', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('monto', models.IntegerField(verbose_name='Monto de la Factura')),
                ('documento', models.CharField(blank=True, choices=[('GUIA', 'Guia'), ('FACTURA', 'Factura'), ('OTRO', 'Otro')], default='S/I', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Adjuntar_Archivo', models.FileField(blank=True, upload_to='guia', verbose_name='Adjuntar Archivo')),
            ],
            options={
                'verbose_name': 'Guia',
                'ordering': ['-id'],
            },
        ),
    ]
