# Generated by Django 3.0.7 on 2020-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_auto_20200626_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='monto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto de la Factura'),
        ),
    ]
