# Generated by Django 2.1 on 2019-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costos',
            name='convenio',
            field=models.CharField(blank=True, choices=[('Convernio Marco', 'CONVENIO MARCO'), ('Licitacion Publica', 'LICITACION PUBLICA'), ('Trato Directo', 'TRATO DIRECTO')], max_length=20, verbose_name='Tipo de Convenio'),
        ),
    ]
