# Generated by Django 2.1 on 2019-10-18 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerofactura', models.CharField(max_length=10, verbose_name='Numero de Factura')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('primerperiodo', models.DateField(default=datetime.date.today, verbose_name='Periodo de lectura 1°')),
                ('segundoperiodo', models.DateField(default=datetime.date.today, verbose_name='Periodo de lectura 2°')),
                ('fechaemision', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emision')),
                ('watts', models.IntegerField(verbose_name='Consumo (watts/m3)')),
                ('total', models.IntegerField(verbose_name='Total ($)')),
                ('sector', models.CharField(max_length=100, verbose_name='Nombre del Sector')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('numeromedidor', models.IntegerField(verbose_name='Numero de Medidor')),
                ('numerocliente', models.IntegerField(verbose_name='Numero de Cliente')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('agualuz', models.CharField(blank=True, choices=[('Agua', 'AGUA'), ('Luz', 'LUZ')], default='SSGG', max_length=10, verbose_name='Servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
