# Generated by Django 2.2.6 on 2019-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunes', '0002_auto_20191106_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunes',
            name='agualuz',
            field=models.CharField(blank=True, choices=[('Agua', 'AGUA'), ('Luz', 'LUZ'), ('Internet', 'INTERNET'), ('Gas', 'GAS'), ('Telefonia', 'TELEFONIA'), ('TV Cable', 'TV CABLE')], default='SSGG', max_length=10, verbose_name='Servicio'),
        ),
    ]
