# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunes', '0003_auto_20191106_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunes',
            options={'ordering': ['-id'], 'verbose_name': 'Factura de Gastos Comunes'},
        ),
    ]
