# Generated by Django 3.0.7 on 2020-07-21 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emsion')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('marca', models.CharField(default='', max_length=255, verbose_name='Marca')),
                ('modelo', models.CharField(default='', max_length=255, verbose_name='Modelo')),
                ('representante', models.CharField(default='', max_length=255, verbose_name='Representante de la Marca')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Adjuntar_Archivo', models.FileField(blank=True, upload_to='manuales', verbose_name='Adjuntar Archivo')),
            ],
            options={
                'verbose_name': 'Manuales',
                'ordering': ['-id'],
            },
        ),
    ]
