# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rrhh',
            options={'ordering': ['-id'], 'verbose_name': 'RRHH'},
        ),
        migrations.AlterField(
            model_name='rrhh',
            name='funcion',
            field=models.CharField(max_length=100, verbose_name='Funcion'),
        ),
    ]
