# Generated by Django 3.0.7 on 2020-09-03 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hhee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha HHEE')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Funcionario')),
                ('hhee', models.CharField(max_length=100, verbose_name='Horas Realizadas')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo de HHEE')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'HHEE',
                'ordering': ['-id'],
            },
        ),
    ]
