# Generated by Django 2.2.6 on 2019-12-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_auto_20191225_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'ordering': ['-id'], 'verbose_name': 'Capacitacion'},
        ),
    ]
