# Generated by Django 2.2.6 on 2019-12-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_auto_20191225_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'ordering': ['id'], 'verbose_name': 'Capacitacion'},
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='Recursos',
            field=models.FileField(blank=True, upload_to='capacitacion', verbose_name='Adjuntar Recurso'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='Adjuntar_Archivo',
            field=models.FileField(blank=True, upload_to='capacitacion', verbose_name='Adjuntar Video'),
        ),
    ]
