# Generated by Django 2.2.6 on 2019-12-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0006_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
