# Generated by Django 2.1 on 2019-10-24 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudestalleresabas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudestalleresabas',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Recepcion MMTTO'),
        ),
        migrations.AlterField(
            model_name='solicitudestalleresabas',
            name='fechaabast',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Abastecimiento'),
        ),
        migrations.AlterField(
            model_name='solicitudestalleresabas',
            name='fechasda',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha SDA'),
        ),
    ]
