# Generated by Django 2.2.6 on 2019-10-30 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudestalleresabas', '0003_auto_20191025_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudestalleresabas',
            name='fecha_Factura',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='E. Factura'),
        ),
        migrations.AddField(
            model_name='solicitudestalleresabas',
            name='fecha_OrdenCompra',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Emsion OC'),
        ),
    ]
