# Generated by Django 2.2.6 on 2019-10-30 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estadoOT',
            field=models.CharField(blank=True, choices=[('Pendiente', 'PENDIENTE'), ('Terminada', 'TERMINADA'), ('Abastecimiento', 'ABASTECIMIENTO'), ('SDA', 'SDA'), ('PROCESO', 'PROCESO')], default='', max_length=20, verbose_name='Estado de Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Recepcion SSGG'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaabast',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Abastecimiento'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fechasda',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha SDA'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='observaciones',
            field=models.TextField(verbose_name='Observaciones'),
        ),
    ]
