# Generated by Django 3.0.7 on 2020-08-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_auto_20200807_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='Adjuntar_Archivo',
            field=models.FileField(blank=True, upload_to='Solicitudes_SSGG_Abast', verbose_name='Adjuntar Archivo'),
        ),
    ]
