# Generated by Django 2.1 on 2019-10-25 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ropaexterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Empresa', models.CharField(max_length=100, verbose_name='Nombre de Empresa')),
                ('Guia', models.CharField(max_length=100, verbose_name='Numero Guia')),
                ('Fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('Detalle', models.CharField(max_length=100, verbose_name='Kilos de Ropa Procesada')),
                ('Cantidad', models.CharField(max_length=100, verbose_name='Cantidad (Kilos)')),
                ('Precio_Unitario', models.CharField(max_length=100, verbose_name='Precio Unitario')),
                ('Valor', models.IntegerField(verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
