# Generated by Django 3.0.7 on 2020-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropaexterno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ropaexterno',
            options={'ordering': ['-id'], 'verbose_name': 'Boleta Confeccion de Ropa'},
        ),
        migrations.AlterField(
            model_name='ropaexterno',
            name='Detalle',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
