# Generated by Django 2.1 on 2019-10-17 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('unidad', models.CharField(max_length=10)),
                ('kmi', models.IntegerField()),
                ('kmf', models.IntegerField()),
                ('kmdt', models.IntegerField()),
                ('combustible', models.IntegerField()),
                ('litros', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('uo', models.CharField(max_length=255)),
                ('pauta1', models.CharField(blank=True, choices=[('SAMU', 'Samu'), ('URGENCIA', 'Urgencia'), ('SSGG', 'ssgg')], default='SSGG', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cartolas del Parque Automotriz',
            },
        ),
    ]
