# Generated by Django 2.1 on 2019-10-17 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='cartola',
            name='combustible',
            field=models.IntegerField(verbose_name='Tipo de Combustible'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='kmdt',
            field=models.IntegerField(verbose_name='Kilometraje Recorrido'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='kmf',
            field=models.IntegerField(verbose_name='Kilometraje Final'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='kmi',
            field=models.IntegerField(verbose_name='Kilometraje Inicial'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='litros',
            field=models.IntegerField(verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='patente',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='pauta1',
            field=models.CharField(blank=True, choices=[('Samu', 'SAMU'), ('Urgencia', 'URGENCIA'), ('ssgg', 'SSGG')], default='SSGG', max_length=10, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='uo',
            field=models.CharField(max_length=255, verbose_name='Unidad de Origen'),
        ),
        migrations.AlterField(
            model_name='cartola',
            name='valor',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
