# Generated by Django 2.1 on 2019-10-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0002_auto_20191017_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='combustible',
            field=models.IntegerField(choices=[('Diesel', 'DIESEL'), ('Bencina', 'BENCINA')], verbose_name='Tipo de Combustible'),
        ),
    ]
