# Generated by Django 2.1 on 2019-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0003_auto_20191017_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='combustible',
            field=models.CharField(choices=[('DIESEL', 'DIESEL'), ('BENCINA', 'BENCINA')], max_length=10, verbose_name='Tipo de Combustible'),
        ),
    ]
