# Generated by Django 2.1 on 2019-10-17 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0004_auto_20191017_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, verbose_name='Patente')),
                ('fechar', models.DateField(default=datetime.date.today, verbose_name='Fecha de Proxima revision Tecnica')),
                ('fechai', models.DateField(default=datetime.date.today, verbose_name='Fecha de Ingreso')),
                ('combustible', models.CharField(choices=[('DIESEL', 'DIESEL'), ('BENCINA', 'BENCINA')], max_length=10, verbose_name='Tipo de Combustible')),
                ('baja', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('kilometraje', models.CharField(max_length=10, verbose_name='Kilometraje de Mantenimiento')),
                ('servicio', models.CharField(blank=True, choices=[('Samu', 'SAMU'), ('Urgencia', 'URGENCIA'), ('ssgg', 'SSGG')], default='SSGG', max_length=10, verbose_name='Servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Inventario Parque Automotriz',
            },
        ),
    ]
