# Generated by Django 2.1 on 2019-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0006_auto_20191018_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviles',
            name='estado',
            field=models.CharField(blank=True, choices=[('Operativa', 'OPERATIVA'), ('Fuera de Servicio', 'FUERA DE SERVICIO')], default='SSGG', max_length=10, verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='marca',
            field=models.CharField(default='Mercedes Benz', max_length=50, verbose_name='Marca del Vehiculo'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='modelo',
            field=models.CharField(default='CDI 4152', max_length=50, verbose_name='Modelo del Vehiculo'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='numerochasis',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Numero de Chasis'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='numeromotor',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Numero de Motor'),
        ),
    ]
