# Generated by Django 2.1 on 2019-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0008_auto_20191018_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviles',
            name='estado',
            field=models.CharField(blank=True, choices=[('Operativa', 'OPERATIVA'), ('Fuera de Servicio', 'FUERA DE SERVICIO')], default='OPERATIVA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='moviles',
            name='modelo',
            field=models.CharField(default='Sprinter 415 CDI', max_length=50, verbose_name='Modelo del Vehiculo'),
        ),
        migrations.AlterField(
            model_name='moviles',
            name='numerochasis',
            field=models.CharField(default='', max_length=50, verbose_name='Numero de Chasis'),
        ),
        migrations.AlterField(
            model_name='moviles',
            name='numeromotor',
            field=models.CharField(default='', max_length=50, verbose_name='Numero de Motor'),
        ),
    ]
