# Generated by Django 2.1 on 2019-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0011_auto_20191023_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='kmdt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraje Recorrido'),
        ),
    ]
