# Generated by Django 2.2.6 on 2020-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssgg', '0013_auto_20200102_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviles',
            name='estado',
            field=models.CharField(blank=True, choices=[('Operativa', 'OPERATIVA'), ('Fuera de Servicio', 'FUERA DE SERVICIO'), ('Baja', 'BAJA')], default='OPERATIVA', max_length=20, verbose_name='Estado'),
        ),
    ]
