# Generated by Django 2.1 on 2019-10-22 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otautomotriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('numeroorden', models.CharField(max_length=100, verbose_name='Numero de OT')),
                ('patente', models.CharField(max_length=10, verbose_name='Patente')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('fechaingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje Ingreso')),
                ('fechaegreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de egreso')),
                ('unidad', models.CharField(blank=True, choices=[('Samu', 'SAMU'), ('Urgencia', 'URGENCIA'), ('Ssgg', 'SSGG')], default='SSGG', max_length=10, verbose_name='Servicio')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('tipo_mantenimiento', models.CharField(blank=True, choices=[('MP', 'Mantenimiento Preventivo'), ('MC', 'Mantenimiento Correctivo')], default='MP', max_length=2, verbose_name='Mantenimiento Preventivo/Correctivo')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
