# Generated by Django 3.0.7 on 2020-08-24 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otautomotriz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otautomotriz',
            options={'ordering': ['-id'], 'verbose_name': 'Ordene de Trabajo del Parque Automotriz'},
        ),
        migrations.AddField(
            model_name='otautomotriz',
            name='Adjuntar_Archivo',
            field=models.FileField(blank=True, upload_to='automotriz', verbose_name='Adjuntar Archivo'),
        ),
        migrations.AlterField(
            model_name='otautomotriz',
            name='fechaegreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Egreso'),
        ),
        migrations.AlterField(
            model_name='otautomotriz',
            name='fechaingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Ingreso'),
        ),
    ]
