# Generated by Django 2.2.4 on 2019-08-20 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('inventario', models.CharField(max_length=100)),
                ('justificacion', models.CharField(max_length=255)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('pauta1', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta2', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta3', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta4', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta5', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta6', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta7', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta8', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta9', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta10', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta11', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta12', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta13', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('pauta14', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
            ],
        ),
    ]
