# Generated by Django 2.2.4 on 2019-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='marca',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='modelo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta15',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='responsable',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='tecnico1',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='tecnico2',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
