# Generated by Django 2.2.1 on 2019-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_auto_20190822_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='pauta16',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta17',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta18',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta19',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta20',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta21',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta22',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta23',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta24',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta25',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta26',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta27',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta28',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta29',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta30',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta31',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta32',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta33',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta34',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta35',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta36',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta37',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta38',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta39',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta40',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta41',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta42',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta43',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta44',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta45',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta46',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta47',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta48',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta49',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta50',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta51',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta52',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta53',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta54',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta55',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta56',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta57',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta58',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta59',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='pauta60',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta1',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta10',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta11',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta12',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta13',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta14',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta15',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta2',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta3',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta4',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta5',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta6',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta7',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta8',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta9',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
    ]
