# Generated by Django 2.2.1 on 2019-08-29 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_monitoreo_nombre1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoreo',
            options={'verbose_name': 'Pautas de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
