# Generated by Django 2.2.1 on 2019-08-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_auto_20190829_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreo',
            name='nombre1',
        ),
    ]
