# Generated by Django 2.2.5 on 2019-09-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_remove_monitoreo_nombre1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreo',
            name='tecnico2',
        ),
    ]
