# Generated by Django 2.2.6 on 2019-11-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0008_remove_monitoreo_tecnico2'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='operativo',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2),
        ),
    ]
