# Generated by Django 2.2.6 on 2019-11-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0009_monitoreo_operativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreo',
            name='operativo',
        ),
    ]
