# Generated by Django 2.2.6 on 2019-11-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0010_remove_monitoreo_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='responsable',
            field=models.CharField(default='Oscar Gonzalez', max_length=255),
        ),
    ]
