# Generated by Django 2.2.6 on 2019-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0013_auto_20191119_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoreo',
            options={'ordering': ['-id'], 'verbose_name': 'Pautas de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='garantia',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Numero de Meses en Garantia'),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='mantencion',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Numero de Mantenciones Anuales'),
        ),
    ]
