# Generated by Django 2.2.6 on 2019-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0014_auto_20191126_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='justificacion',
            field=models.CharField(blank=True, default='S/O', max_length=255),
        ),
    ]
