# Generated by Django 2.2.6 on 2019-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0015_auto_20191126_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='inventario',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='marca',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='modelo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='nombre',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='serie',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='servicio',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
