# Generated by Django 2.2.6 on 2019-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0016_auto_20191204_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='inventario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='servicio',
            field=models.CharField(max_length=100),
        ),
    ]
