# Generated by Django 2.2.6 on 2019-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0018_auto_20191205_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta12',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('N/A', 'N/A')], default='SI', max_length=3),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='pauta56',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('N/A', 'N/A')], default='SI', max_length=3),
        ),
    ]
