# Generated by Django 2.1 on 2019-10-21 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerofactura', models.CharField(max_length=10, verbose_name='Numero de Factura')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Recepcion')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
                ('monto', models.IntegerField(verbose_name='Monto de la Factura')),
                ('numeroordencompra', models.CharField(max_length=10, verbose_name='Numero de OC')),
                ('estadofactura', models.CharField(blank=True, choices=[('Pendiente', 'PENDIENTE'), ('Pagada', 'PAGADA'), ('Abastecimiento', 'ABASTECIMIENTO'), ('SDA', 'SDA')], default='', max_length=20, verbose_name='Estado de Factura')),
                ('fechaemision', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emision')),
                ('fechatramitacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de tramitacion')),
                ('servicio', models.TextField(verbose_name='Servicio Prestado')),
                ('detalle', models.TextField(verbose_name='Detalle del trabajo realizado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
