# Generated by Django 2.1 on 2019-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20191023_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='estadofactura',
            field=models.CharField(blank=True, choices=[('Pendiente', 'PENDIENTE'), ('Pagada', 'PAGADA'), ('Abastecimiento', 'ABASTECIMIENTO'), ('SDA', 'SDA'), ('Proceso', 'PROCESO')], default='', max_length=20, verbose_name='Estado de Factura'),
        ),
    ]
