# Generated by Django 2.1 on 2019-10-21 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerofolio', models.CharField(blank=True, max_length=10, verbose_name='Numero de Folio')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha OT')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('serviciosolicita', models.CharField(blank=True, choices=[('66', 'HOSPITALIZACIÓN MEDICINA INTERNA'), ('90', 'HOSPITALIZACIÓN QUIRÚRGICA'), ('96', 'HOSPITALIZACIÓN UROLOGÍA'), ('100', 'HOSPITALIZACIÓN OTORRINOLARINGOLOGÍA'), ('111', 'HOSPITALIZACIÓN TRAUMATOLOGÍA'), ('113', 'HOSPITALIZACIÓN OBSTETRICIA'), ('114', 'HOSPITALIZACIÓN GINECOLOGÍA'), ('116', 'HOSPITALIZACIÓN PEDIATRÍA'), ('117', 'HOSPITALIZACIÓN NEONATOLOGÍA'), ('131', 'HOSPITALIZACIÓN CIRUGÍA PEDIÁTRICA'), ('159', 'HOSPITALIZACIÓN DE DIA'), ('180', 'UNIDAD DE CUIDADOS INTERMEDIOS ADULTOS'), ('195', 'UNIDAD DE TRATAMIENTO INTENSIVO ADULTO'), ('205', 'EMERGENCIAS ADULTO'), ('215', 'EMERGENCIAS GINECO OBSTÉTRICAS'), ('216', 'EMERGENCIAS PEDIÁTRICAS'), ('232', 'CONSULTA OTROS PROFESIONALES'), ('273', 'CONSULTA MEDICINA INTERNA'), ('274', 'CONSULTA NEUROLOGÍA'), ('280', 'CONSULTA PSIQUIATRÍA'), ('285', 'CONSULTA NEFROLOGÍA'), ('290', 'CONSULTA GASTROENTEROLOGÍA'), ('294', 'PROGRAMA MANEJO DEL DOLOR'), ('295', 'CONSULTA SALUD OCUPACIONAL'), ('296', 'CONSULTA ANESTESIA'), ('302', 'PROGRAMA ENFERMEDADES DE TRANSMISIÓN SEXUAL'), ('309', 'CONSULTA CIRUGÍA GENERAL'), ('311', 'CONSULTA UROLOGÍA'), ('317', 'CONSULTA OFTALMOLOGÍA'), ('319', 'CONSULTA OTORRINOLARINGOLOGÍA'), ('321', 'CONSULTA MÉDICA DE TRAUMATOLOGÍA'), ('328', 'CONSULTA PEDIATRÍA GENERAL'), ('331', 'CONSULTA NEUROLOGÍA PEDIÁTRICA'), ('342', 'CONSULTA TRAUMATOLOGÍA PEDIÁTRICA'), ('351', 'CONSULTA CIRUGÍA PEDIÁTRICA'), ('353', 'CONSULTA GINECOLOGICA'), ('354', 'CONSULTA OBSTETRICIA'), ('356', 'CONSULTA ODONTOLOGÍA'), ('357', 'EMERGENCIAS ODONTOLOGICAS'), ('359', 'TELEMEDICINA'), ('462', 'QUIRÓFANOS CABEZA Y CUELLO'), ('364', 'QUIRÓFANOS CARDIOVASCULAR'), ('465', 'QUIRÓFANOS DE EMERGENCIA'), ('467', 'QUIRÓFANOS DIGESTIVA'), ('470', 'QUIRÓFANOS GINECOLOGÍA'), ('476', 'QUIRÓFANOS OBSTETRICIA'), ('477', 'QUIRÓFANOS ODONTOLOGICA'), ('478', 'QUIRÓFANOS OFTALMOLOGÍA'), ('480', 'QUIRÓFANOS OTORRINOLARINGOLOGÍA'), ('482', 'QUIRÓFANOS PLÁSTICA'), ('485', 'QUIRÓFANOS TRAUMATOLOGÍA Y ORTOPEDIA'), ('486', 'QUIRÓFANOS UROLOGÍA'), ('493', 'QUIRÓFANOS CIRUGÍA PLÁSTICA'), ('240', 'PROCEDIMIENTO DE CARDIOLOGÍA'), ('244', 'PROCEDIMIENTO DE NEUMOLOGÍA'), ('248', 'PROCEDIMIENTOS DE CARDIOLOGÍA'), ('250', 'PROCEDIMIENTOS DE GASTROENTEROLOGÍA'), ('251', 'PROCEDIMIENTOS DE GINECOLOGÍA'), ('256', 'PROCEDIMIENTOS DE OBSTETRICIA'), ('257', 'PROCEDIMIENTOS DE ODONTOLOGÍA'), ('258', 'PROCEDIMIENTOS DE OFTALMOLOGÍA'), ('261', 'PROCEDIMIENTOS DE OTORRINOLARINGOLOGÍA'), ('262', 'PROCEDIMIENTOS DE TRAUMATOLOGÍA'), ('263', 'PROCEDIMIENTOS DE UROLOGÍA'), ('267', 'PROCEDIMIENTOS ENDOSCÓPICOS'), ('471', 'QUIRÓFANOS MAYOR AMBULATORIA'), ('517', 'SALAS DE PARTO'), ('518', 'LABORATORIO CLÍNICO'), ('531', 'TOMA DE MUESTRA'), ('540', 'MAMOGRAFÍA'), ('541', 'TOMOGRAFÍA'), ('542', 'IMAGENOLOGÍA'), ('544', 'ANATOMÍA PATOLÓGICA'), ('567', 'REHABILITACIÓN'), ('593', 'SERVICIO FARMACEUTICO'), ('644', 'AMBULANCIA'), ('648', 'ASEO'), ('652', 'SERVICIO DE ALIMENTACIÓN'), ('567', 'REHABILITACIÓN'), ('657', 'LAVANDERIA Y ROPERIA'), ('644', 'TRANSPORTE GENERAL'), ('713', 'TRABAJO SOCIAL'), ('660', 'ADMINISTRACIÓN'), ('567', 'REHABILITACIÓN'), ('657', 'LAVANDERIA Y ROPERIA')], default='SSGG', max_length=50, verbose_name='Servicio que Solicita')),
                ('estadoOT', models.CharField(blank=True, choices=[('Pendiente', 'PENDIENTE'), ('Terminada', 'TERMINADA'), ('Abastecimiento', 'ABASTECIMIENTO'), ('SDA', 'SDA')], default='', max_length=20, verbose_name='Estado de la OT')),
                ('valormano', models.IntegerField(verbose_name='Valor Mano de Obra')),
                ('valormateriales', models.IntegerField(verbose_name='Valor de Materiales')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
