# Generated by Django 2.1 on 2019-10-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='estadoOT',
            field=models.CharField(blank=True, choices=[('Pendiente', 'PENDIENTE'), ('Terminada', 'TERMINADA'), ('Abastecimiento', 'ABASTECIMIENTO'), ('SDA', 'SDA'), ('PROCESO', 'PROCESO')], default='', max_length=20, verbose_name='Estado de la OT'),
        ),
    ]
