# Generated by Django 2.2.6 on 2020-04-15 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emsion')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('servicio', models.CharField(default='', max_length=255, verbose_name='Unidad/Servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Adjuntar_Archivo', models.FileField(blank=True, upload_to='control', verbose_name='Adjuntar Archivo')),
            ],
            options={
                'verbose_name': 'Control',
                'ordering': ['-id'],
            },
        ),
    ]
