# Generated by Django 2.2.6 on 2020-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='desde',
            field=models.CharField(blank=True, default='S/I', max_length=255, verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='control',
            name='documento',
            field=models.CharField(blank=True, choices=[('MEMO', 'Memo'), ('INFORME', 'Informe'), ('ORDINARIO', 'Ordinario'), ('RESOLUCION', 'Resolucion')], default='S/I', max_length=50),
        ),
        migrations.AddField(
            model_name='control',
            name='hacia',
            field=models.CharField(blank=True, default='S/I', max_length=255, verbose_name='Hacia'),
        ),
    ]
