# Generated by Django 2.2.6 on 2020-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20200415_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='desde',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Desde'),
        ),
        migrations.AlterField(
            model_name='control',
            name='hacia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hacia'),
        ),
    ]
