# Generated by Django 2.2.6 on 2020-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20200415_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='documento',
            field=models.CharField(blank=True, choices=[('MEMO', 'Memo'), ('INFORME', 'Informe'), ('ORDINARIO', 'Ordinario'), ('RESOLUCION', 'Resolucion'), ('OTRO', 'Otro')], default='S/I', max_length=50),
        ),
    ]
