# Generated by Django 2.2.6 on 2020-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20200415_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='servicio',
        ),
        migrations.AddField(
            model_name='control',
            name='recepcion',
            field=models.CharField(default='', max_length=255, verbose_name='Recepcionado Por:'),
        ),
    ]
