# Generated by Django 2.2.6 on 2020-04-15 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20200415_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='fecharecepcion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Recepcion'),
        ),
    ]
