# Generated by Django 2.2.6 on 2020-01-10 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clima',
            options={'ordering': ['-id'], 'verbose_name': 'Inventario de Equipos de Climatizacion'},
        ),
        migrations.AddField(
            model_name='clima',
            name='estado',
            field=models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('Baja', 'BAJA')], default='B', max_length=5, verbose_name='Condicion del Equipo'),
        ),
        migrations.AddField(
            model_name='clima',
            name='fecha_baja',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
